hibernate:
  connection:
    autoommit: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secure
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    show-sql: true